### ISSUE TITLE
Investigate Marketplace endpoints

### ISSUE THREAD

**Issue by CalumW1** [CalumW1/R6StatAPI#13]
**What needs to be done:**
- Investigate what endpoints exist to possibly add marketplace API calls in.

**Comment by foxyyyyyyyyyyyyy** [comment]
that would be realy cool

**Comment by CalumW1** [comment]
Marketplace endpoints are all using GraphQL, I have created a folder in Postman for them. I have found 6 queries so far that i think would be good: 

1. Search
2. Item Details
3. Pending Transactions
4. Transaction History
5. Recommended Items
6. Sellable Items

Ill need to do some more research into GraphQL as i don't know much about it, but this is a good start.
